### ISSUE TITLE
Feature: Make RMD Dynamically Parameterized by Users and Orgs

### ISSUE THREAD

**Issue by jimbrig** [jimbrig/github-issue-table#2]
Add Params:

i.e.

```yaml
params:
  users: jimbrig
  orgs: 
    - jimbrig-work
    - tychobra
    - powwater
```
